apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
components:
    - ../../../../components/project-admin-rolebindings/grok-micro
    - ../../../../components/resourcequotas/small
    - ../../../../components/limitranges/default
namespace: grok-micro
