apiVersion: kustomize.config.k8s.io/v1beta1
components:
- ../../../../components/project-admin-rolebindings/baaas
- ../../../../components/limitranges/default
- ../../../../components/resourcequotas/small
kind: Kustomization
namespace: baaas-dfs
resources:
- namespace.yaml
