apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: smaug
  title: Smaug
  description: Smaug is a public operate first cluster open to user applications and workloads
  annotations:
    operate-first.cloud/logo-url: https://upload.wikimedia.org/wikipedia/commons/3/3a/OpenShift-LogoType.svg
    prometheus.io/alert: all
    prometheus.io/labels: "managed_cluster_id=91976abd-8b8e-47b9-82d3-e84793396ed7a,category=service_availability"

  links:
    - url: https://console-openshift-console.apps.smaug.na.operate-first.cloud/
      title: Smaug cluster OCP console
      icon: web
spec:
  type: cluster
  lifecycle: production
  owner: group:operate-first
