supportChannelId: C01RMPVUUK1
onCall:
  schedule: daily
  members:
    - slack: U01SKRUKCM6
      github: 4n4nd
    - slack: U02580V036C
      github: Gregory-Pereira
    - slack: U01SW975LQY
      github: harshad16
    - slack: U01RF5SASLX
      github: HumairAK
    - slack: U02C0MN9YDC
      github: dystewart
github:
  issues:
    access:
      - operate-first/apps
      - operate-first/support
      - operate-first/SRE
    labels:
      - kind/question
